services:
  - type: web
    name: shagomer
    runtime: docker
    plan: free
    dockerfilePath: ./WebApplication1/WebApplication1/Dockerfile
    dockerContext: ./WebApplication1/WebApplication1
    healthCheckPath: /
